name: contro
description: "Flutter Project by ITCoderz. Flutter SDK version for the app is 3.22.2"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  chalkdart: ^2.2.1
  flutter_spinkit: ^5.2.1
  dropdown_button2: ^2.3.9
  pinput: ^5.0.0
  country_code_picker: ^3.0.0
  syncfusion_flutter_charts: ^26.1.41
  data_table_2: ^2.5.15
  dotted_line: ^3.2.2
  flutter_advanced_switch: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter_icons:
  image_path: "assets/app_icon/contro_app_icon_changed_color.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/app_icon/
    - assets/icons/
    - assets/fonts/sf_pro_text/
    - assets/fonts/hind/
    - assets/fonts/poppins/
    - assets/bottom_navigation_icons/
    - assets/images/


  fonts:
    - family: SfProText
      fonts:
        - asset: assets/fonts/sf_pro_text/SFProText-Bold.ttf
        - asset: assets/fonts/sf_pro_text/SFProText-Light.ttf
        - asset: assets/fonts/sf_pro_text/SFProText-Medium.ttf
        - asset: assets/fonts/sf_pro_text/SFProText-Regular.ttf

    - family: Hind
      fonts:
        - asset: assets/fonts/hind/Hind-Bold.ttf
        - asset: assets/fonts/hind/Hind-Light.ttf
        - asset: assets/fonts/hind/Hind-Medium.ttf
        - asset: assets/fonts/hind/Hind-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf



